### ISSUE TITLE
Breaking Facebook and Twitter Layouts

### ISSUE THREAD

**Issue by neteinstein** [dippas/DeleteNonio#7] opened 2020-08-05 11:48 UTC
**Describe the bug**
If you add this currently with the new version of Chrome and use the new Facebook layout it won't allow you to scroll.. even if you limit the plugin just to other websites.

Twitter in dark mode also gets broken

**To Reproduce**
1. Update Chrome
2. Install Plugin
3. Go To Facebook
4. Change to new layout
5. You can't scroll anymore

**Screenshots**
- https://share.getcloudapp.com/OAuqO2Qg

**Desktop (please complete the following information):**
 - Chrome Version 84.0.4147.105 (Official Build) (64-bit) for MacOS

**Comment by dippas** [comment] 2020-08-05 11:50
@neteinstein  fixed in v1.6.1 (please read the [changelog](https://github.com/dippas/DeleteNonio/releases), chrome webstores is taking a while to approve new version.

**Closed by dippas** 2020-08-05 11:50 UTC
Labels: duplicate, good first issue

**Comment by dippas** [comment] 2020-08-05 11:57
Duplicate of #5

**Comment by dippas** [comment] 2020-08-06 11:36
@neteinstein a extensão já está atualizada pode verificar está tudo OK?

**Comment by neteinstein** [comment] 2020-08-06 14:16
Fixed 👍
